#!/bin/sh
MODULE=Kahua

while [ $# -gt 0 ]; do
  case $1 in
    gen) gen=yes; shift ;;
    tgz) tgz=yes; shift ;;
    test) test=yes; shift ;;
    testclean) testclean=yes; shift ;;
    *) echo "DIST [gen][tgz][test][testclean]"; exit 0;;
  esac
done

if [ "$gen" = "yes" ]; then
  autoconf -I `gauche-config --ac`
  (cd examples; autoconf -I `gauche-config --ac`)
  svnversion >REVISION
fi

if [ "$tgz" = "yes" ]; then
  if [ -f Makefile ]; then make maintainer-clean; fi
  autoconf -I `gauche-config --ac`
  (cd examples; autoconf -I `gauche-config --ac`)
  svnversion >REVISION
  ./configure
  (cd doc; make html)
  make distclean

  if [ ! -f VERSION ]; then echo "No VERSION; something wrong?"; exit 1; fi
  VERSION=`cat VERSION`

  rm -f DIST_EXCLUDE_X
  cat DIST_EXCLUDE > DIST_EXCLUDE_X
  find . -name CVS -o -name .svn -print -prune >> DIST_EXCLUDE_X

  rm -rf ../$MODULE-$VERSION

  mkdir ../$MODULE-$VERSION
  tar cvfX - DIST_EXCLUDE_X . | (cd ../$MODULE-$VERSION; tar xf -)
  (cd ..; tar cvf - $MODULE-$VERSION | gzip -9 > $MODULE-$VERSION.tgz)
fi

